//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgII_VideoClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public Articulo()
        {
            this.Renta_Devolucion = new HashSet<Renta_Devolucion>();
        }
    
        public int ID { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Tipo_de_articulo_ID { get; set; }
        public Nullable<int> Idioma_ID { get; set; }
        public Nullable<double> Renta_por_dia { get; set; }
        public string Dias_de_renta { get; set; }
        public Nullable<double> Monto_entrega_tardia { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Renta_Devolucion> Renta_Devolucion { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual Tipo_de_artículo Tipo_de_artículo { get; set; }
        public virtual Elenco_articulo Elenco_articulo { get; set; }
    }
}
