//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgII_VideoClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Renta_Devolucion = new HashSet<Renta_Devolucion>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public Nullable<int> Num_tarjeta_CR { get; set; }
        public Nullable<double> Limite_de_credito { get; set; }
        public string Tipo_persona { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Renta_Devolucion> Renta_Devolucion { get; set; }
    }
}
