//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgII_VideoClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elenco_articulo
    {
        public int Articulo { get; set; }
        public Nullable<int> Elenco { get; set; }
        public string Rol { get; set; }
    
        public virtual Articulo Articulo1 { get; set; }
        public virtual Elenco Elenco1 { get; set; }
    }
}
