//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgII_VideoClub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoClub_dbEntities : DbContext
    {
        public VideoClub_dbEntities()
            : base("name=VideoClub_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Empleado> Empleados { get; set; }
        public DbSet<Genero> Generos { get; set; }
        public DbSet<Renta_Devolucion> Renta_Devolucion { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Tipo_de_artículo> Tipo_de_artículo { get; set; }
        public DbSet<Idioma> Idiomas { get; set; }
        public DbSet<Articulo> Articulos { get; set; }
        public DbSet<Elenco> Elencoes { get; set; }
        public DbSet<Elenco_articulo> Elenco_articulo { get; set; }
    }
}
