//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgII_VideoClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renta_Devolucion
    {
        public int Num_de_renta { get; set; }
        public Nullable<int> Empleado { get; set; }
        public Nullable<int> Articulo { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<System.DateTime> Fecha_renta { get; set; }
        public Nullable<System.DateTime> Fecha_devolucion { get; set; }
        public Nullable<double> Renta_por_dia { get; set; }
        public string Dias_de_renta { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Articulo Articulo1 { get; set; }
    }
}
